[package]
name = "Secp256k1_Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = {version="0.21.2", features = ["rand"]}
sha2 = "0.10.1"
hex-literal = "0.3.4"